name: youtube_download
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  youtube_data_api: ^1.0.4
  get: ^4.6.6
  persistent_bottom_nav_bar: ^5.0.2
  google_nav_bar: ^5.0.6
  ionicons: ^0.2.2
  youtube_explode_dart: ^1.12.4
  logger: ^2.2.0
  url_launcher: ^6.2.6
  http: ^0.13.6
  cached_network_image: ^3.3.1
  easy_refresh: ^3.3.4
  flutter_file_downloader: ^1.2.1
  lottie: ^3.0.0
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  # ios: true
  android : true
  image_path : "assets/images/iconApp.png"
  # image_path_ios: "assets/images/iconApp.jpg"


launcher_name:
  default: "Earth Horizon"
  ar: "افق الارض" 
  
flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/images/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
